1.1 nav to signup page
raphaella-rose/acebook-eta pull request #13
Opened 2022-07-15 14:48 UTC by nazhudha

Added Signup and Sign-in buttons to navigate between pages, with Cypress tests

2022-07-15 15:02 UTC, davekempsell approved these changes
looks good, not sure what the .DS_Store file is that's causing a conflict? Haven't seen that before

2022-07-15 15:45 UTC, raphaella-rose requested changes
Hey guys, looks good but there are a couple of changes I think need to be made. I'm around for a bit to talk through the comments! :)

2022-07-15 15:45 UTC, raphaella-rose commented on views/home/index.hbs
> +  <input type="submit" value="Sign Up" />
This could be a link <a> instead for simpler code as it's a get request.

2022-07-15 15:45 UTC, raphaella-rose commented on views/home/index.hbs
> +<form action="./sessions/new" method="GET">
This could be a link instead for simpler code as it's a get request.

2022-07-15 15:45 UTC, raphaella-rose commented on views/layout.hbs
> +    {{!-- <form action='/sessions?_method=DELETE' method='POST'>
Is this commented out? Why?

2022-07-15 15:45 UTC, raphaella-rose commented on views/sessions/new.hbs
> +<form action="/" method="GET">
This could be a link instead for simpler code as it's a get request.

2022-07-15 15:45 UTC, raphaella-rose commented on views/users/new.hbs
> +<form action="/" method="GET">
This could be a link instead for simpler code as it's a get request.

2022-07-18 09:28 UTC, closed without merging

2022-07-18 09:28 UTC, nazhudha commented
.DS_Store conflict, resubmit pull request